{
 "title": "Sensor data",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT pressure, \"time\" FROM sensor_data LIMIT 50 "
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT humidity, \"time\" FROM sensor_data LIMIT 50 "
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT temperature, \"time\" FROM sensor_data LIMIT 50 "
    }
   ]
  }
 ]
}